server.port: 8282
my.greeting: Islam
app.name: My App
app.description: ${app.name}
color: One,Two,Three
db.connection: db connection from default
db.port: 1200
db.host: 127.0.0.1

management.endpoints.web.expose.include: "*"
spring.profiles.active: test
spring.application.name: application
spring.cloud.config.uri: http://localhost:8888
management.security.enable: false


